version: 2

project_name: dashboard

before:
  hooks:
    - go mod tidy
    - go tool templ generate

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

kos:
  - repositories: ["ghcr.io/ben-burwood/dashboard"]
    tags:
      - "{{.Version}}"
      - latest
    bare: true
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
